apiVersion: v1
kind: ConfigMap
metadata:  
  name: test-yasya-terbaru
  labels:    
    app.kubernetes.io/name: test-yasya-terbaru
    app: test-yasya-terbaru
  annotations: 
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave : "-5"
data:
  ENVIRONMENT: ""
